/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    posts: Post;
    sectors: Sector;
    pitches: Pitch;
    subscribers: Subscriber;
    syndication: Syndication;
    theses: Thesis;
    'exemplar-candidates': ExemplarCandidate;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    sectors: SectorsSelect<false> | SectorsSelect<true>;
    pitches: PitchesSelect<false> | PitchesSelect<true>;
    subscribers: SubscribersSelect<false> | SubscribersSelect<true>;
    syndication: SyndicationSelect<false> | SyndicationSelect<true>;
    theses: ThesesSelect<false> | ThesesSelect<true>;
    'exemplar-candidates': ExemplarCandidatesSelect<false> | ExemplarCandidatesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Bot users can only ever create and edit drafts.
   */
  roles: ('admin' | 'bot')[];
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  /**
   * Auto-generated from the title if left blank.
   */
  slug: string;
  /**
   * Shown as the standfirst under the title, and in listings.
   */
  excerpt: string;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Every factual claim in the post must trace to one of these.
   */
  sources: {
    title: string;
    url: string;
    publisher?: string | null;
    dateAccessed?: string | null;
    id?: string | null;
  }[];
  publishedDate: string;
  featuredImage?: (number | null) | Media;
  geography: 'global' | 'india' | 'united-states';
  assetClass: 'private-equity' | 'venture-capital' | 'cross';
  /**
   * Create a new sector if none of the existing ones fit.
   */
  sector: number | Sector;
  /**
   * What made you write this, or what surprised you while writing it. One or two sentences, in your voice. This is the first thing a subscriber reads, and the announcement cannot be sent without it. Never shown on the site.
   */
  newsletterNote?: string | null;
  /**
   * Set automatically when the announcement goes out.
   */
  newsletterSentAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Post sectors. Add a new one whenever a post needs it.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sectors".
 */
export interface Sector {
  id: number;
  name: string;
  /**
   * Auto-generated from the name if left blank.
   */
  slug: string;
  /**
   * Optional. Shown on sector browse pages later.
   */
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Research pitches. Set one to "Selected" and the drafter will pick it up.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pitches".
 */
export interface Pitch {
  id: number;
  title: string;
  /**
   * The specific argument this post would make.
   */
  angle: string;
  /**
   * What in the last two weeks makes this timely.
   */
  whyNow: string;
  /**
   * Paths into the blog-research repo backing this pitch.
   */
  researchPaths?:
    | {
        path: string;
        id?: string | null;
      }[]
    | null;
  candidateSources: {
    title: string;
    url: string;
    publisher?: string | null;
    dateAccessed?: string | null;
    id?: string | null;
  }[];
  geography: 'global' | 'india' | 'united-states';
  assetClass: 'private-equity' | 'venture-capital' | 'cross';
  /**
   * Empty if the agent proposed a sector that does not exist yet.
   */
  suggestedSector?: (number | null) | Sector;
  /**
   * A proposed new sector name. Create it in Sectors, then link it above.
   */
  suggestedSectorName?: string | null;
  postFormat: 'sharp-take' | 'thesis';
  /**
   * Set to "Selected" to have the drafter write this one.
   */
  status: 'proposed' | 'selected' | 'drafted' | 'rejected';
  /**
   * Set by the drafter. Its presence is what prevents double-drafting.
   */
  linkedPost?: (number | null) | Post;
  draftedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Newsletter subscribers. Added by the public form, never editable by it.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscribers".
 */
export interface Subscriber {
  id: number;
  email: string;
  status: 'pending' | 'confirmed' | 'unsubscribed';
  /**
   * Slug of the post the reader subscribed from, or "home".
   */
  source?: string | null;
  confirmToken?: string | null;
  unsubscribeToken?: string | null;
  confirmedAt?: string | null;
  unsubscribedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Platform-native drafts to paste by hand, and the performance numbers you enter afterwards.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "syndication".
 */
export interface Syndication {
  id: number;
  /**
   * Set from the post title when the draft is created.
   */
  label?: string | null;
  /**
   * A post syndication argues one thread of a published post. A research original argues a corpus item that never became one, and carries no link.
   */
  kind: 'post-syndication' | 'research-original';
  post?: (number | null) | Post;
  /**
   * What this one is about. Names the row in the list view.
   */
  topic?: string | null;
  /**
   * Paths into blog-research backing a research original, in the same form a pitch uses. Provenance: without them there is no way to check the claims months later.
   */
  sourceAnchors?:
    | {
        path: string;
        id?: string | null;
      }[]
    | null;
  platform: 'linkedin';
  /**
   * Queued means the routine has not written it yet.
   */
  status: 'queued' | 'drafted' | 'posted' | 'skipped';
  /**
   * The post exactly as it will be pasted. First line is the hook and must survive the mobile fold at ~140 characters. No link in here: it goes in the first comment.
   */
  body?: string | null;
  /**
   * Posted as the first comment immediately after the post itself, carrying the blog URL. This is what keeps the link out of the post body. Left empty on a research original: there is no post to send anyone to, and a loosely related link spends the reach on a click that disappoints.
   */
  linkComment?: string | null;
  /**
   * Recorded so the metrics below can eventually answer whether the first-comment workaround is worth its lower click-through.
   */
  linkPlacement?: ('first-comment' | 'in-post') | null;
  /**
   * When you actually pasted it. The metric buckets count from here.
   */
  postedAt?: string | null;
  /**
   * Paste the URL of the live post so the numbers can be re-checked.
   */
  postUrl?: string | null;
  /**
   * LinkedIn has no impressions API for personal profiles, so these are entered by hand from the post analytics panel. Take one at 48 hours, one at 7 days, one at 30 days.
   */
  metrics?:
    | {
        bucket: '48h' | '7d' | '30d';
        capturedAt: string;
        impressions?: number | null;
        reactions?: number | null;
        comments?: number | null;
        reposts?: number | null;
        /**
         * Clicks on the first-comment link, if LinkedIn reports them.
         */
        linkClicks?: number | null;
        id?: string | null;
      }[]
    | null;
  /**
   * What you changed before posting, or anything about the post that would explain its numbers later.
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Long-form theses, one a month. Set one to "Active" and the routine works through its stages.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "theses".
 */
export interface Thesis {
  id: number;
  /**
   * The subject, not the argument. The argument is decided at stage 1.
   */
  topic: string;
  /**
   * The framing you want, in your words. Say what the topic is NOT, when the name is ambiguous: this is what stops stage 1 researching the wrong thing for a week.
   */
  brief?: string | null;
  /**
   * Required on a routine proposal. Optional on one you write yourself.
   */
  whyNow?: string | null;
  /**
   * What each stage produced. Written by the routine, newest last.
   */
  artifacts?:
    | {
        stage: number;
        path: string;
        /**
         * The stage in a few lines.
         */
        summary?: string | null;
        /**
         * The full artifact, as committed to blog-research.
         */
        content?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Your decisions at each gate, and the steer you gave.
   */
  reviews?:
    | {
        stage: number;
        decision: 'approved' | 'blocked';
        note?: string | null;
        decidedAt?: string | null;
        id?: string | null;
      }[]
    | null;
  geography?: ('global' | 'india' | 'united-states') | null;
  /**
   * Also picks the exemplar domain the routine reads: venture-capital reads exemplars/vc, private-equity reads exemplars/pe, cross reads exemplars/macro.
   */
  assetClass?: ('private-equity' | 'venture-capital' | 'cross') | null;
  sector?: (number | null) | Sector;
  /**
   * YYYY-MM. Which month this one is for.
   */
  targetMonth?: string | null;
  /**
   * Set to "Active" to start it. Only one should be active at a time.
   */
  status: 'proposed' | 'active' | 'published' | 'dropped';
  /**
   * The NEXT stage to run. 1 scope, 2 market, 3 counter-case, 4 model, 5 spine, 6 draft, 7 recommend. Gates after 1, 4 and 5.
   */
  stage: number;
  /**
   * Use the Approve and Block buttons rather than this. Awaiting review auto-advances after 48 hours so a quiet month still ships.
   */
  stageStatus: 'ready' | 'awaiting-review' | 'blocked' | 'done';
  /**
   * When the current stage status was set. The 48 hour clock counts from here.
   */
  stageEnteredAt?: string | null;
  proposedBy?: ('human' | 'routine') | null;
  /**
   * Set by stage 6. Its presence is what prevents double-drafting.
   */
  linkedPost?: (number | null) | Post;
  updatedAt: string;
  createdAt: string;
}
/**
 * Research the harvest wants to tear down. Approve the ones worth imitating; declining with a reason is just as useful.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exemplar-candidates".
 */
export interface ExemplarCandidate {
  id: number;
  /**
   * Set from the publisher and URL when the routine proposes it.
   */
  title?: string | null;
  publisher: string;
  url: string;
  /**
   * Which gap in the coverage grid this fills, and what it teaches structurally. This is what you are judging.
   */
  why?: string | null;
  /**
   * Why this is not worth imitating. Recorded so the same piece is never proposed again, which makes declining as useful as approving.
   */
  declineReason?: string | null;
  /**
   * Set by the harvest once the teardown is written.
   */
  teardownPath?: string | null;
  domain: 'vc' | 'pe' | 'macro';
  kind?: ('thesis' | 'market-map' | 'case-study' | 'annual-letter' | 'diligence-memo' | 'regime-read') | null;
  /**
   * Comma separated.
   */
  industries?: string | null;
  /**
   * Approved gets torn down on the next harvest. Unreachable means the routine could not read it, usually bot protection.
   */
  status: 'proposed' | 'approved' | 'declined' | 'unreachable' | 'done';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'sectors';
        value: number | Sector;
      } | null)
    | ({
        relationTo: 'pitches';
        value: number | Pitch;
      } | null)
    | ({
        relationTo: 'subscribers';
        value: number | Subscriber;
      } | null)
    | ({
        relationTo: 'syndication';
        value: number | Syndication;
      } | null)
    | ({
        relationTo: 'theses';
        value: number | Thesis;
      } | null)
    | ({
        relationTo: 'exemplar-candidates';
        value: number | ExemplarCandidate;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  roles?: T;
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  content?: T;
  sources?:
    | T
    | {
        title?: T;
        url?: T;
        publisher?: T;
        dateAccessed?: T;
        id?: T;
      };
  publishedDate?: T;
  featuredImage?: T;
  geography?: T;
  assetClass?: T;
  sector?: T;
  newsletterNote?: T;
  newsletterSentAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sectors_select".
 */
export interface SectorsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pitches_select".
 */
export interface PitchesSelect<T extends boolean = true> {
  title?: T;
  angle?: T;
  whyNow?: T;
  researchPaths?:
    | T
    | {
        path?: T;
        id?: T;
      };
  candidateSources?:
    | T
    | {
        title?: T;
        url?: T;
        publisher?: T;
        dateAccessed?: T;
        id?: T;
      };
  geography?: T;
  assetClass?: T;
  suggestedSector?: T;
  suggestedSectorName?: T;
  postFormat?: T;
  status?: T;
  linkedPost?: T;
  draftedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscribers_select".
 */
export interface SubscribersSelect<T extends boolean = true> {
  email?: T;
  status?: T;
  source?: T;
  confirmToken?: T;
  unsubscribeToken?: T;
  confirmedAt?: T;
  unsubscribedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "syndication_select".
 */
export interface SyndicationSelect<T extends boolean = true> {
  label?: T;
  kind?: T;
  post?: T;
  topic?: T;
  sourceAnchors?:
    | T
    | {
        path?: T;
        id?: T;
      };
  platform?: T;
  status?: T;
  body?: T;
  linkComment?: T;
  linkPlacement?: T;
  postedAt?: T;
  postUrl?: T;
  metrics?:
    | T
    | {
        bucket?: T;
        capturedAt?: T;
        impressions?: T;
        reactions?: T;
        comments?: T;
        reposts?: T;
        linkClicks?: T;
        id?: T;
      };
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "theses_select".
 */
export interface ThesesSelect<T extends boolean = true> {
  topic?: T;
  brief?: T;
  whyNow?: T;
  artifacts?:
    | T
    | {
        stage?: T;
        path?: T;
        summary?: T;
        content?: T;
        id?: T;
      };
  reviews?:
    | T
    | {
        stage?: T;
        decision?: T;
        note?: T;
        decidedAt?: T;
        id?: T;
      };
  geography?: T;
  assetClass?: T;
  sector?: T;
  targetMonth?: T;
  status?: T;
  stage?: T;
  stageStatus?: T;
  stageEnteredAt?: T;
  proposedBy?: T;
  linkedPost?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exemplar-candidates_select".
 */
export interface ExemplarCandidatesSelect<T extends boolean = true> {
  title?: T;
  publisher?: T;
  url?: T;
  why?: T;
  declineReason?: T;
  teardownPath?: T;
  domain?: T;
  kind?: T;
  industries?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}